account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'account'
urlpatterns = [
    path('admin_dashboard/', views.AdminDashboard.as_view(), name='admin_dashboard'),
    path('customer_dashboard/', views.CustomerDashboard.as_view(), name='customer_dashboard'),
    path('add_product/', views.AddProductView.as_view(), name='add_product'),
    path('edit_product/<pk>/', views.EditProductView.as_view(), name='edit_product'),
    path('delete_product/<pk>/', views.delete_product, name='delete_product'),
    path('delete_customer/<pk>/', views.DeleteCustomerView.as_view(), name='delete_customer'),
    path('order_detail/<pk>/', views.CustomerOrderDetails.as_view(), name='order_detail'),
    path('change_password_customer/', views.CustomerChangePasswordView.as_view(), name='change_password_customer'),
    path("logout/", views.logout_user, name="logout"),
    # path("logout/", auth_views.LogoutView.as_view(next_page="/login/"), name="logout"),
]

basket/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

from . import views

app_name = 'basket'
urlpatterns = [
    path('', views.basket_summary, name='basket_summary'),
    path('basket_add/', views.basket_add, name='basket_add'),
    path('delete/', views.basket_delete, name='basket_delete'),
    path('checkout_order/', views.checkout_order, name='checkout_order'),
    path('order_successful/', views.order_successful, name='order_successful'),
]

frontend/urls.py
from django.urls import path, include

from . import views

app_name = 'frontend'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('store/products/', views.AllProductView.as_view(), name='all_products'),
    path('store/product/details/<pk>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('register/', views.RegisterUserView.as_view(), name='register'),
    path('login/', views.LoginUserView.as_view(), name='login'),
]

gb_machinary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontend.urls', namespace='frontend')),
    path('account/', include('account.urls', namespace='account')),
    path('order/', include('order.urls', namespace='order')),
    path('basket/', include('basket.urls', namespace='basket')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

order/urls.py
from django.urls import path, include

from . import views

app_name = 'order'
urlpatterns = [
    path('edit_order/<pk>/', views.EditOrderView.as_view(), name='edit_order'),
    path('delete_order/<pk>/', views.delete_order, name='delete_order'),
    path('view_receipt/<pk>/', views.view_receipt, name='view_receipt'),
]

templates/includes/footer.html
<!-- footer -->
<section id="footer">
    <div class="container py-5">
      <div class="row">
        <div class="col-md-5">
          <h3>GLOBAL MACHINARY</h3>
          <p>705 W 62nd Ave. Denver, CO, 80216 United States</p>
          <p><strong>Phone: </strong>352-547-5160</p>
          <p><strong>Email: </strong>contact@globalmachinary.com</p>
        </div>
        <div class="col-md-3 wish-links">
          <h3>Helpful Links</h3>
          <a href="{% url 'frontend:about' %}">About Us</a>
          <a href="{% url 'frontend:about' %}">Services</a>
          <a href="">Resources</a>
          <a href="{% url 'frontend:contact' %}">Contact</a>
        </div>
        <div class="col-md-4 wish-links">
          <h3>Useful Links</h3>
          <a href="{% url 'frontend:all_products' %}">Products</a>
          <a href="">Careers</a>
          <a href="">Customers</a>
        </div>
      </div>
      <hr>
      <p class="text-center">Copyrights 2023 | Global Machinary</p>
    </div>
</section>

templates/includes/navbar.html
{% load static %}

<!-- Navbar -->
<nav class="navbar navbar-expand-lg fixed-top scroll2">
    <div class="container">
      <a class="navbar-brand" href="#"><img src="{% static 'images/logo-mg-logo.png' %}" class="logo-logo"><img src="{% static 'images/logo-mg-text.png' %}" class="logo-text"></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mx-auto mb-2 mb-lg-0">
          {% if not request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'frontend:home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'frontend:about' %}">About</a>
          </li>
          <!-- <li class="nav-item">
            <a class="nav-link" href="#">Service</a>
          </li> -->
          <li class="nav-item">
            <a class="nav-link" href="{% url 'frontend:all_products' %}">Products</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'frontend:all_products' %}">Products</a>
          </li>
            {% if request.user.is_staff%}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'account:admin_dashboard' %}">Dashboard</a>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'account:customer_dashboard' %}">Dashboard</a>
              </li>
            {% endif %}
          {% endif %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'frontend:contact' %}">Contact</a>
          </li>
          <li class="nav-item mt-md-2 pe-2">
            <div id="google_translate_element"></div>
          </li>
        </ul>
        {% if request.user.is_authenticated %}
          <a href="{% url 'account:logout' %}" class="btn btn-danger fw-bold rounded-pill px-4 ms-5 mb-5 mb-sm-0">Logout</a>
        {% else %}
          <a href="{% url 'frontend:register' %}" class="btn btn-danger fw-bold rounded-pill px-4 mb-5 mb-sm-0">Register</a>
          <a href="{% url 'frontend:login' %}" class="btn btn-danger fw-bold rounded-pill px-4 ms-5 mb-5 mb-sm-0">Login</a>
        {% endif %}
        <a type="button" role="button" href="{% url 'basket:basket_summary' %}" data-bs-toggle="tooltip" data-bs-placement="bottom"
          data-bs-custom-class="custom-tooltip" data-bs-title="Click to View Cart Items"  class=" border-0 basket-btn px-4">
            {% with total_qty=basket|length %}
            <div id="basket-qty" class="basket-qty">
              {% if total_qty > 0 %}
              {{ total_qty }}
              {% else %}
              0
              {% endif %}
            </div>
            {% endwith %}
            <div>
              <i class="bi bi-cart cart-icon"></i>
            </div>
          </a>
      </div>
    </div>
</nav>

<!-- btn btn-outline-secondary -->