basket/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

from . import views

app_name = 'basket'
urlpatterns = [
    path('', views.basket_summary, name='basket_summary'),
    path('basket_add/', views.basket_add, name='basket_add'),
    path('delete/', views.basket_delete, name='basket_delete'),
    path('checkout_order/', views.checkout_order, name='checkout_order'),
    path('order_successful/', views.order_successful, name='order_successful'),
]

frontend/urls.py
from django.urls import path, include

from . import views

app_name = 'frontend'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('store/products/', views.AllProductView.as_view(), name='all_products'),
    path('store/product/details/<pk>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('register/', views.RegisterUserView.as_view(), name='register'),
    path('login/', views.LoginUserView.as_view(), name='login'),
]

gb_machinary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontend.urls', namespace='frontend')),
    path('account/', include('account.urls', namespace='account')),
    path('order/', include('order.urls', namespace='order')),
    path('basket/', include('basket.urls', namespace='basket')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

order/urls.py
from django.urls import path, include

from . import views

app_name = 'order'
urlpatterns = [
    path('edit_order/<pk>/', views.EditOrderView.as_view(), name='edit_order'),
    path('delete_order/<pk>/', views.delete_order, name='delete_order'),
    path('view_receipt/<pk>/', views.view_receipt, name='view_receipt'),
]

frontend/models.py
from django.db import models

# Create your models here.

frontend/forms.py
from django import forms


class ContactForm(forms.Form):
    name = forms.CharField(max_length=200)
    email = forms.EmailField()
    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea(attrs={'rows':4, 'cols':15}),)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control mb-3'})

frontend/views.py
from django.contrib import messages
from django.shortcuts import render
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from django.contrib.auth.views import LoginView
from django.contrib.auth import login 
from django.views.generic import ListView, TemplateView, FormView, DetailView
from django.conf import settings

from . import emails
from . import forms

from store.models import Product, Media
from account.forms import RegistrationForm, UserLoginForm 



class HomeView(ListView):
    redirect_authenticated_user = True
    model = Product
    context_object_name = 'products'
    template_name = 'frontend/index.html'
    paginate_by= 8

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            if request.user.is_staff:
                return HttpResponseRedirect(reverse_lazy('account:admin_dashboard'))
            else:
                return HttpResponseRedirect(reverse_lazy('account:customer_dashboard'))
        return super().dispatch(request, *args, **kwargs)

    # def get_context_data(self, **kwargs):
    #    context = super(HomeView, self).get_context_data(**kwargs)
    #    return context


class AboutView(TemplateView):
    redirect_authenticated_user = True
    template_name = 'frontend/about.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            if request.user.is_staff:
                return HttpResponseRedirect(reverse_lazy('account:admin_dashboard'))
            else:
                return HttpResponseRedirect(reverse_lazy('account:customer_dashboard'))
        return super().dispatch(request, *args, **kwargs)


class AllProductView(ListView):
    model = Product
    context_object_name = 'products'
    template_name = 'frontend/products.html'


class ProductDetailView(DetailView):
    model = Product
    context_object_name = 'product'
    template_name = 'frontend/product_detail.html'

    def get_context_data(self, **kwargs):
       context = super(ProductDetailView, self).get_context_data(**kwargs)
       context['product_images'] = Media.objects.filter(product=self.object)
       return context


class ContactView(FormView):
    form_class = forms.ContactForm 
    success_url = reverse_lazy('frontend:contact')
    template_name = 'frontend/contact.html'  

    def form_valid(self, form):
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']

            final_message = render_to_string('emails/email_contact.html', 
                            {
                                'name': name,
                                'email': email,
                                'message': message,
                                'subject': subject
                            })

            if email and message and name:
                try:
                    emails.email_message_send(
                        'Message from '+ name,
                        final_message,
                        'contact@globalmachinary.com',
                    )
                    messages.success(self.request, "Your message was sent successfully, we will get back to you shortly")
                except:
                    messages.error(self.request, 'Something went wrong, please make sure your email is correct and try again')  
            else:
                message.error(self.request, 'Make sure all fields are entered and valid.')  
        return super(ContactView, self).form_valid(form)


class RegisterUserView(FormView):
    form_class = RegistrationForm
    redirect_authenticated_user = True
    success_url = reverse_lazy('frontend:login')
    template_name = 'frontend/register.html'

    def form_valid(self, form):
        user = form.save(commit=False)
        user.set_password(form.cleaned_data["password"])
        user.save()
        messages.success(self.request, "Your account was created successfully, please login below")
        return super(RegisterUserView, self).form_valid(form)
    

class LoginUserView(LoginView):
    redirect_authenticated_user = True
    template_name = 'frontend/login.html'
    form_class = UserLoginForm

    def get_success_url(self):
        if self.request.user.is_staff:
            return reverse_lazy('account:admin_dashboard')
        else:
            return reverse_lazy('account:customer_dashboard')
    
    def form_invalid(self, form):
        messages.error(self.request,'Invalid Email or password, please try again')
        return self.render_to_response(self.get_context_data(form=form))

templates/frontend/about.html
{% extends '../base.html' %}
{% load static %}

{% block content %}

<!-- banner -->
<div class="banner-about">
    <div class="container py-5">
      <div class="row justify-content-center align-items-center py-5 mt-3">
          <div class="col-8">
              <h3 class="text-center"><a href="">Home</a>/ About </h3>
          </div>
      </div>
    </div>
</div>


<!-- card sirt -->
<section id="about-us">
    <div class="container py-5">
      <div class="row py-2">
        <div class="col-md-6">
          <h1 class="text-danger">Who We are!</h1>
          <h3 class="text-primary">Our History</h3>
          <hr>
          <p class="lead fw-bold">Providing an incident-free workplace is at the core of everything we do and is part of our commitment to deliver innovative, reliable, and efficient services to our customers. Through our focus on managing high risk activities, being data driven and leadership engagement, we proactively pursue reliable controls to prevent incidents and to safeguard the welfare of our employees, customers, communities, suppliers, and the environment. From training to execution, Parker employees prove daily that "no hurts, no spills, and zero recordable incidents" is achievable. We believe in "doing the job right…every time."</p>
          <ul>
            <li>Our team helps customers better manage costs and mitigate risks through the provision of advanced safety equipments, efficient, and cost-effective operation of both our global fleet of drilling rigs equipment and also by operating and maintaining customer-owned rig</li>
            <li>Our team takes pride in delivering services that meet our customer's exact requirements, by prioritizing Safety Tools, Procedural Discipline, Competency, Audit and Assessment, and Key Performance Indicators</li>
            <li>Our name says a lot about who we are. We serve customers all over the world. We have the same pride in our products that citizens have in their state. We strive to be the market leader and provider of choice for oilfield tool sales, rentals, manufacturing and service.</li>
            <li>We manufacture and distribute top oilfield tools for oil and water well drilling and provide service to keep your equipment running smoothly.</li>
          </ul>

        </div>
        <div class="col-md-6">
            <img src="{% static 'images/worker1.jpg' %}" alt="" class="img-fluid img-swell mb-5">
            <img src="{% static 'images/workers.jpg' %}" alt="" class="img-fluid img-swell">
        </div>
      </div>
    </div>
  </section>


  <!-- mode section -->
  <section id="mode-section">
    <div class="container pt-5 pb-3 text-white">
      <div class="row">
        <div class="col-md-6"></div>
        <div class="col-md-6">
          <h2>WE MANUFACTURE, REFURBISH AND RE-CERTIFY EQUIPMENT FOR LAND AND OFFSHORE DRILLING RIGS.</h2>
          <p>Proper inspection and testing is critical to keeping your equipment operational and safe. With all of our after sale services, we strive for quality, excellence and your satisfaction.
          Our equipments are certified in Magnetic Particle Inspection (MPI) and Load Tested by API standards.
          </p>
          <p>Thanks to our professional services, quality products, fast delivery and competitive prices, we have built up a very good reputation among our customers. Our products are serving for customers from more than 40 countries, like USA, Venezuela, Argentina, India, Kazakhstan, Uzbekistan, Azerbaijan, Romania, China, Syria and Egypt etc.. </p>
        </div>
        
      </div>
    </div>
  </section>

  
  <!-- mode section -->
  <section id="mode-section-2">
    <div class="container pt-5 pb-3 text-white">
      <div class="row py-5">
        <div class="col-md-6">
          <h3 class="text-info">--  LOCATION</h3> 
          <h1>Our International Markets</h1>
          <p>From Alaska to Colombia, Europe, Africa to the Middle East and around the world, GB has the products, services and expertise to ensure your drilling operation runs efficiently and safely.</p>
          <p>We are always ready to help solve the subsurface energy challenges of today and tomorrow, wherever and whatever they may be.</p>
        </div>
        <div class="col-md-6">
            <img src="{% static 'images/worker3.jpg' %}" alt="" class="img-fluid" style="opacity: 0.3;">
        </div>
        
      </div>
    </div>
  </section>

  <!-- company we work with -->
<section id="compay-with">
    <div class="container py-5">
      <h1 class="text-center text-danger mb-5">
        Some Of Our Regular Customers
      </h1>
      <div class="row bg-light">
        <div class="col-3 work-with">
          <img src="{% static 'images/aramco.png' %}" alt="" class="img-fluid">
        </div>
        <div class="col-3 work-with">
          <img src="{% static 'images/snpmf.png' %}" alt="" class="img-fluid">
        </div>
        <div class="col-3 work-with">
          <img src="{% static 'images/exxonmobile.png' %}" alt="" class="img-fluid" >
        </div>
        <div class="col-3 work-with">
          <img src="{% static 'images/pccyf.png' %}" alt="" class="img-fluid">
        </div>
      </div>
    </div>
  </section>

  
{% endblock %}

templates/frontend/contact.html
{% extends '../base.html' %}
{% load static %}

{% block content %}
<!-- register form -->
<section id="contact">
    <div class="container py-5">
        <div class="row justify-content-center align-items-center py-5">
            <div class="col-md-6 py-md-5">
                <div class="card shadow">
                    <!-- <center>
                        <a class="navbar-brand" href="#"><img src="{% static 'images/logo-mg-logo.png' %}" class="logo-logo"></a>
                    </center> -->
                    {% if form.errors %}
                        <p class="text-white fw-bold">Please correct the following errors:</p>
                        {% for field in form %}
                            {% if field.errors %}
                            <div class="alert alert-primary" role="alert">
                                {{ field.label }}: {{ field.errors|striptags }}
                            </div>
                            {% endif %}
                        {% endfor %}
                    {% endif %}
    
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-success alert-dismissible fade show" role="alert">
                                {{message}}
                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            </div>
                        {% endfor %}
                    {% endif %}
                    
                    <h2 class="card-title text-info mt-3 ms-4">Contact Us</h2>
                    <hr class="mt-0">
                    <div class="card-body">
                        <form action="." method="POST">
                            {% csrf_token %}
                            {{form.as_p}}
                            
                            <input type="submit" value="Send" class="btn btn-danger fw-bold px-5 w-100 h-auto">
    
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

templates/frontend/index.html
{% extends '../base.html' %}
{% load static %}
{% load humanize %}

{% block content %}

<style>
  .p-card img{
    height: 200px;
    object-fit: cover;
  }
</style>

<!-- banner -->
<div class="banner">
    <div id="carouselExampleCaptions" class="carousel slide carousel-fade" data-bs-ride="carousel" data-bs-interval="2000">
      <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="3" aria-label="Slide 4"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="4" aria-label="Slide 5"></button>
      </div>
      <div class="carousel-inner">
        <div class="carousel-item active">
          <div class="overlay"></div>
          <video src="{% static 'images/video-five.mp4' %}" autoplay loop muted class="d-block w-100 img-fluid"></video>
          <div class="carousel-caption">
            <h5>ENGINEERING EQUIPMENTS</h5>
            <p>Global Machinary Offshore Wind Market Report provides a comprehensive review and outlook of global and regional offshore wind spending and installation activity on a quarterly basis.</p>
            <p><a href="">Get Started Now</a></p>
          </div>
        </div>
        <div class="carousel-item">
          <div class="overlay"></div>
          <video src="{% static 'images/video-two.mp4' %}" autoplay loop muted class="d-block w-100 img-fluid"></video>
          <div class="carousel-caption">
            <h5>ENGINEERING EQUIPMENTS</h5>
            <p>The leading source of commercial offshore rig data and intelligence, trusted by leading E&P companies, rig contractors, OFS companies, and financial sector advisors worldwide.</p>
            <p><a href="{% url 'frontend:all_products' %}">Get Started</a></p>
          </div>
        </div>
        <div class="carousel-item ">
          <div class="overlay"></div>
          <video src="{% static 'images/video-one.mp4' %}" autoplay loop muted class="d-block w-100 img-fluid"></video>
          <div class="carousel-caption">
            <h5>ENGINEERING EQUIPMENTS</h5>
            <p>Global Machinary Offshore Wind Market Report provides a comprehensive review and outlook of global and regional offshore wind spending and installation activity on a quarterly basis.</p>
            <p><a href="">Get Started</a></p>
          </div>
        </div>
        <div class="carousel-item">
          <div class="overlay"></div>
          <img src="{% static 'images/hero2.jpg' %}" class="d-block w-100" alt="...">
          <div class="carousel-caption">
            <h5>ENGINEERING EQUIPMENTS</h5>
            <p>The leading source of commercial offshore rig data and intelligence, trusted by leading E&P companies, rig contractors, OFS companies, and financial sector advisors worldwide</p>
            <p><a href="">Get Started</a></p>
          </div>
        </div>
        <div class="carousel-item">
          <div class="overlay"></div>
          <img src="{% static 'images/hero3.jpg' %}" class="d-block w-100" alt="...">
          <div class="carousel-caption">
            <h5>ENGINEERING EQUIPMENTS</h5>
            <p>Global Machinary Offshore Wind Market Report provides a comprehensive review and outlook of global and regional offshore wind spending and installation activity on a quarterly basis.</p>
            <p><a href="">Get Started</a></p>
          </div>
        </div>
      </div>
    </div>
</div>


<!-- card sirt -->
<section id="about-us">
    <div class="container py-5">
      <div class="row py-2">
        <div class="col-md-6">
          <h1 class="text-danger">About Us</h1>
          <h3 class="text-primary">Global Machine Overview</h3>
          <hr>
          <p class="lead fw-bold">At Global Machines, we have been a trusted by our partners to supply original and strong engineering equipments, with a team dedicated to continually finding the best solution to our customer's operational challenges.</p>
          <ul>
            <li>Our team helps customers better manage costs and mitigate risks through the provision of advanced safety equipments, efficient, and cost-effective operation of both our global fleet of drilling rigs equipment and also by operating and maintaining customer-owned rig</li>
            <li>Our team takes pride in delivering services that meet our customer's exact requirements, by prioritizing Safety Tools, Procedural Discipline, Competency, Audit and Assessment, and Key Performance Indicators</li>
            <li>Our name says a lot about who we are. We serve customers all over the world. We have the same pride in our products that citizens have in their state. We strive to be the market leader and provider of choice for oilfield tool sales, rentals, manufacturing and service.</li>
            <li>We manufacture and distribute top oilfield tools for oil and water well drilling and provide service to keep your equipment running smoothly.</li>
          </ul>
          <a href="{% url 'frontend:all_products' %}" class="btn btn-danger fw-bold rounded-pill w-50 mt-3">Learn More</a>

        </div>
        <div class="col-md-6">
          <img src="{% static 'images/worker1.jpg' %}" alt="" class="img-fluid img-swell mb-5">
          <img src="{% static 'images/workers.jpg' %}" alt="" class="img-fluid img-swell">
        </div>
      </div>
    </div>
  </section>

  <!-- mode section -->
  <section id="mode-section">
    <div class="container pt-5 pb-3 text-white">
      <div class="row">
        <div class="col-md-6"></div>
        <div class="col-md-6">
          <h2>WE MANUFACTURE, REFURBISH AND RE-CERTIFY EQUIPMENT FOR LAND AND OFFSHORE DRILLING RIGS.</h2>
          <p>Proper inspection and testing is critical to keeping your equipment operational and safe. With all of our after sale services, we strive for quality, excellence and your satisfaction.
          Our equipments are certified in Magnetic Particle Inspection (MPI) and Load Tested by API standards.
          </p>
          <p>Thanks to our professional services, quality products, fast delivery and competitive prices, we have built up a very good reputation among our customers. Our products are serving for customers from more than 40 countries, like USA, Venezuela, Argentina, India, Kazakhstan, Uzbekistan, Azerbaijan, Romania, China, Syria and Egypt etc.. </p>
        </div>
        
      </div>
    </div>
  </section>

  <!-- products -->
  <section id="products">
    <div class="container py-5">
      <h1 class="text-center text-danger mb-5">Top Sales</h1>
      <div class="row">
        {% for product in products %}
        <div class="col-md-3 mb-4 ">
          <div class="card  p-card h-100">
            {% for imgg in product.media.all %}
              {% if imgg.is_featured %}
              <img src="{{imgg.image.url}}" class="card-img-top">
              {% endif %}
            {% endfor %}
            <div class="card-body card-body-smile" >
              <h5 class="card-title">{{product.title| slice:'0:31'}}....</h5>
              <p class="card-text fw-bold">Price: ${{product.price|intcomma}}</p>
              <a href="{% url 'frontend:product_detail' product.id %}" class="btn btn-danger fw-bold btn-sm w-100 h-auto">View Details</a>
            </div>
           
          </div>
        </div>
        {% endfor %}
      </div>
      <hr>
      <div class="d-grid gap-2 d-md-flex justify-content-md-center">
        <a href="{% url 'frontend:all_products' %}" class="btn btn-danger fw-bold rounded-pill px-5">View More Products</a>
      </div>
      
    </div>
</section>


<!-- mode section -->
<section id="mode-section-2">
    <div class="container pt-5 pb-3 text-white">
      <div class="row py-5">
        <div class="col-md-6">
          <h3 class="text-info">--  LOCATION</h3> 
          <h1>Our International Markets</h1>
          <p>From Alaska to Colombia, Europe, Africa to the Middle East and around the world, GB has the products, services and expertise to ensure your drilling operation runs efficiently and safely.</p>
          <p>We are always ready to help solve the subsurface energy challenges of today and tomorrow, wherever and whatever they may be.</p>
        </div>
        <div class="col-md-6">
          <img src="{% static 'images/worker3.jpg' %}" alt="" class="img-fluid" style="opacity: 0.3;">
        </div>
        
      </div>
    </div>
</section>

<!-- company we work with -->
<section id="compay-with">
    <div class="container py-5">
      <h1 class="text-center text-danger mb-5">
        Some Of Our Regular Customers
      </h1>
      <div class="row bg-light">
        <div class="col-3 work-with">
          <img src="{% static 'images/aramco.png' %}" alt="" class="img-fluid">
        </div>
        <div class="col-3 work-with">
          <img src="{% static 'images/snpmf.png' %}" alt="" class="img-fluid">
        </div>
        <div class="col-3 work-with">
          <img src="{% static 'images/exxonmobile.png' %}" alt="" class="img-fluid" >
        </div>
        <div class="col-3 work-with">
          <img src="{% static 'images/pccyf.png' %}" alt="" class="img-fluid">
        </div>
      </div>
    </div>
  </section>


{% endblock %}

templates/frontend/product_detail.html
{% extends '../base.html' %}
{% load static %}
{% load humanize %}

{% block content %}
<style>
  #ProductImg{
    height: 450px;
    object-fit: cover;
  }
  .small-img{
    height: 110px;
    width: 130px;
    object-fit: cover;
  }
  @media only screen and (max-width:767px) {
    #ProductImg{
      height: 300px;
    }
    .small-img{
      height: 80px;
    }
  }
</style>

<!-- banner -->
<div class="banner-product-detail">
    <div class="container py-5">
      <div class="row justify-content-center align-items-center py-5 mt-3">
          <div class="col-8">
              <h3 class="text-center"><a href="">Home</a>/ Product Details </h3>
          </div>
      </div>
    </div>
</div>

<!-- details -->
<div class="container py-5">
  <div class="row py-4">
    <!-- <h5>product.name</h5> -->
    <div class="col-md-6">
      {% for imgg in product.media.all %}
        {% if imgg.is_featured %}
        <img src="{{imgg.image.url}}" class="card-img-top" id="ProductImg">
        {% endif %}
      {% endfor %}
      <div class="row mt-4">
        {% for image in product_images %}
        <div class="col-3 mb-2">
          <img src="{{image.image.url}}" class="img-fluid small-img">
        </div>
        {% endfor %}
      </div>
    </div>

    <div class="col-md-6">
      <h3>{{product.title}}</h3>
      <hr class="mt-0">
      <h3 class="text-primary">Description</h3>   
      <p>{{product.description}}</p>
      <hr class="mt-0">
      <h3>Prize: ${{product.price|intcomma}}</h3>
        <div class="mb-3">
          <label for="form-select" class="form-label fw-bold">Quantity</label>
          <select id="qty-select" class="form-select" aria-label="Default select example">
              <!-- <label for="floatingInput">Email address</label> -->
              <option value="1" selected>1</option>
              <option value="2">2</option>
              <option value="3">3</option>
              <option value="4">4</option>
              <option value="5">5</option>
              <option value="6">6</option>
              <option value="7">7</option>
              <option value="8">8</option>
              <option value="9">9</option>
              <option value="10">10</option>
          </select>
        </div>
      
      <div id="bt-alert" class=" text-success fw-bold"></div>
      <!-- <div id="bt-alert" class="alert alert-success alert-dismissible fade show btt-alert" role="alert">
        Item is successfully added to card
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div> -->
      <button value="{{product.id}}" id="add-button" class="btn btn-secondary fw-bold btn-sm mt-4 w-50 h-auto">Add To Cart</button>
    </div>
  </div>
</div>




  
  <!-- mode section -->
  <section id="mode-section-2">
    <div class="container pt-5 pb-3 text-white">
      <div class="row py-5">
        <div class="col-md-6">
          <h3 class="text-info">--  LOCATION</h3> 
          <h1>Our International Markets</h1>
          <p>From Alaska to Colombia, Europe, Africa to the Middle East and around the world, GB has the products, services and expertise to ensure your drilling operation runs efficiently and safely.</p>
          <p>We are always ready to help solve the subsurface energy challenges of today and tomorrow, wherever and whatever they may be.</p>
        </div>
        <div class="col-md-6">
            <img src="{% static 'images/worker3.jpg' %}" alt="" class="img-fluid" style="opacity: 0.3;">
        </div>
        
      </div>
    </div>
  </section>

<script>
  var ProductImg = document.getElementById("ProductImg");
    var SmallImg = document.getElementsByClassName("small-img");
    for(let i = 0; i < SmallImg.length; i++){
        SmallImg[i].onclick = function()
        {
            ProductImg.src = SmallImg[i].src;
        }
    }
</script>


<!-- getting the product to add to cart -->
<script>
  $(document).on('click', '#add-button', function (e) {
    e.preventDefault();
    console.log($('#add-button').val())
    $.ajax({
      type: 'POST',
      url: '{% url "basket:basket_add" %}',
      data: {
        productid: $('#add-button').val(),
        qty: $('#qty-select option:selected').text(),
        csrfmiddlewaretoken: "{{csrf_token}}",
        action: 'post'
      },
      success: function (json) {
        document.getElementById("basket-qty").innerHTML = json.qty
        document.getElementById("bt-alert").innerHTML = "Item is successfuly added to cart"
      },
      error: function (xhr, errmsg, err) {}
    });
  })
</script>
{% endblock %}

templates/frontend/products.html
{% extends '../base.html' %}
{% load static %}
{% load humanize %}

{% block content %}
<style>
    .p-card img{
      height: 200px;
      object-fit: cover;
    }
</style>


<!-- banner -->
<div class="banner-about">
  <div class="container py-5">
    <div class="row justify-content-center align-items-center py-5 mt-3">
        <div class="col-8">
            <h3 class="text-center"><a href="/">Home</a>/ Available Products </h3>
        </div>
    </div>
  </div>
</div>


<!-- products -->
<section id="products">
    <div class="container py-5">
      <h1 class="text-center text-danger mb-5">Available Products</h1>
      <div class="row">
        {% for product in products %}
        <div class="col-md-3 mb-4 ">
          <div class="card  p-card h-100">
            {% for imgg in product.media.all %}
              {% if imgg.is_featured %}
              <img src="{{imgg.image.url}}" class="card-img-top">
              {% endif %}
            {% endfor %}
            <div class="card-body card-body-smile" >
              <h6 class="card-title">{{product.title| slice:'0:22'}}....</h6>
              <p class="card-text fw-bold">Price: ${{product.price|intcomma}}</p>
              <a href="{% url 'frontend:product_detail' product.id %}" class="btn btn-danger fw-bold btn-sm w-100 h-auto">View Details</a>
            </div>
           
          </div>
        </div>
        {% endfor %}
      </div>
      <hr>
      <div class="d-grid gap-2 d-md-flex justify-content-md-center">
        <a href="{% url 'frontend:all_products' %}" class="btn btn-danger fw-bold rounded-pill px-5">View More Products</a>
      </div>
      
    </div>
</section>
{% endblock %}