basket/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

from . import views

app_name = 'basket'
urlpatterns = [
    path('', views.basket_summary, name='basket_summary'),
    path('basket_add/', views.basket_add, name='basket_add'),
    path('delete/', views.basket_delete, name='basket_delete'),
    path('checkout_order/', views.checkout_order, name='checkout_order'),
    path('order_successful/', views.order_successful, name='order_successful'),
]

frontend/urls.py
from django.urls import path, include

from . import views

app_name = 'frontend'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('store/products/', views.AllProductView.as_view(), name='all_products'),
    path('store/product/details/<pk>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('register/', views.RegisterUserView.as_view(), name='register'),
    path('login/', views.LoginUserView.as_view(), name='login'),
]

gb_machinary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontend.urls', namespace='frontend')),
    path('account/', include('account.urls', namespace='account')),
    path('order/', include('order.urls', namespace='order')),
    path('basket/', include('basket.urls', namespace='basket')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

order/urls.py
from django.urls import path, include

from . import views

app_name = 'order'
urlpatterns = [
    path('edit_order/<pk>/', views.EditOrderView.as_view(), name='edit_order'),
    path('delete_order/<pk>/', views.delete_order, name='delete_order'),
    path('view_receipt/<pk>/', views.view_receipt, name='view_receipt'),
]

basket/models.py
from django.db import models

# Create your models here.

basket/views.py
from django.http import JsonResponse
from django.contrib import messages
from django.shortcuts import get_object_or_404, render, redirect
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils.http import urlencode

from .basket import Basket
from store.models import Product
from account.forms import ClientForm
from order.models import Order, OrderItem
from frontend import emails


def basket_summary(request):
    basket = Basket(request)
    form = ClientForm()
    return render(request, 'basket/summary.html', {'basket': basket, 'form':form})


def basket_add(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        qty = int(request.POST.get('qty'))
        product = get_object_or_404(Product, id=product_id)
        basket.add(product=product, qty=qty)

        basketqty = basket.__len__()
        response = JsonResponse({'qty': basketqty})
        return response
    

def basket_delete(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        basket.delete(product=product_id)

        basketqty = basket.__len__()
        baskettotal = basket.get_total_price()
        shippingtotal = basket.get_shipping_price()
        response = JsonResponse({'qty': basketqty, 'subtotal': baskettotal, 'shipping':shippingtotal})
        return response
    

def checkout_order(request):
    basket = Basket(request)
    form = ClientForm(request.POST)
    if form.is_valid():
        customer = form.save()
        baskettotal = basket.get_total_price()
        basketsubtotal = basket.get_subtotal_price()
        basketshipping = basket.get_shipping_price()
        
        if request.user.is_authenticated:
            user_id = request.user.id
            order = Order.objects.create(user_id=user_id, full_name=customer.c_full_name, 
                    email=customer.   c_email, country=customer.c_country, city=customer.c_city, total=baskettotal, sub_total=basketsubtotal, shipping_price=basketshipping)
            order_id = order.pk
            for item in basket:
                OrderItem.objects.create(order_id=order_id, product=item['product'], price=item['price'], 
                                         quantity=item['qty'])
                
            f_message = render_to_string('emails/email_order.html', 
                            {
                                'name': customer.c_full_name,
                                'order_id': order.pk,
                                'date': order.created,
                                'country': customer.c_country,
                                'city': customer.c_city,
                                'total': basket.get_total_price()
                            })
            try:
                emails.email_message_send(
                    'Order Successful',
                    f_message,
                    customer.c_email,
                )
            except:
                pass 
            finally:
                # return redirect('basket:order_successful') 
                basket.clear()
                redirect_url = reverse('basket:order_successful')
                parameters = urlencode({'obj': order.pk})
                return redirect(f'{redirect_url}?{parameters}')
        else:
            order = Order.objects.create(full_name=customer.c_full_name, 
                    email=customer.   c_email, country=customer.c_country, total=baskettotal, sub_total=basketsubtotal, shipping_price=basketshipping)
            order_id = order.pk
            for item in basket:
                OrderItem.objects.create(order_id=order_id, product=item['product'], price=item['price'], quantity=item['qty'])

            f_message = render_to_string('emails/email_order.html', 
                            {
                                'name': customer.c_full_name,
                                'order_id': order.pk,
                                'date': order.created,
                                'country': customer.c_country,
                                'city': customer.c_city,
                                'total': basket.get_total_price()
                            })
            try:
                emails.email_message_send(
                    'Order Successful',
                    f_message,
                    customer.c_email,
                )
            except:
                pass 
            finally:
                # return redirect('basket:order_successful')
                basket.clear()
                redirect_url = reverse('basket:order_successful')
                parameters = urlencode({'obj': order.pk})
                return redirect(f'{redirect_url}?{parameters}')
    else:
        messages.error(request, 'Something went wrong, please check the form informations and try again')
        return redirect('basket:basket_summary')
    

def order_successful(request):
    order_slug = request.GET.get('obj')
    order = Order.objects.get(pk=order_slug)
    order_items = OrderItem.objects.filter(order=order)
    
    if not request.POST:
        f_message = render_to_string('emails/email_admin_order.html', 
            {
                'name': order.full_name,
                'email': order.email,
                'date': order.created,
                'items': order_items,
                'country': order.country,
                'total': order.get_final_balance()
            })
        try:
            emails.email_message_send(
                        'New Order Placed',
                        f_message,
                        'contact@globalmachinary.com',
                    )
        except:
                pass 

    context = {'order_items':order_items, 'order':order}
    return render(request, 'basket/order_successful.html', context)
    

templates/basket/order_successful.html
{% extends '../base.html' %}
{% load static %}
{% load humanize %}

{% block content %}

<!-- banner -->
<div class="banner-about">
    <div class="container py-5">
      <div class="row justify-content-center align-items-center py-5 mt-3">
          <div class="col-8">
              <h3 class="text-center"><a href="">Home</a>/ Cart Items Summary </h3>
          </div>
      </div>
    </div>
</div>


<div class="container py-5">
    <div class="row justify-content-center align-items-center py-5">
        <div class="col-md-6">
            <div class="card bg-light shadow">
                <div class="card-body">
                    <center>
                        <i class="bi bi-check-circle" style="font-size: 140px; color: green;"></i>
                    </center>
                    <p class="fw-bold text-center">Your Order was placed Successfully. <br>
                        Please check your email for further instructions on how to make payment.
                        Thank you.
                    </p>
                    

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/basket/summary.html
{% extends '../base.html' %}
{% load static %}
{% load humanize %}

{% block content %}

<!-- banner -->
<div class="banner-about">
    <div class="container py-5">
      <div class="row justify-content-center align-items-center py-5 mt-3">
          <div class="col-8">
              <h3 class="text-center"><a href="">Home</a>/ Cart Items Summary </h3>
          </div>
      </div>
    </div>
</div>


<section class="h-100 h-custom" style="background-color: #eee;">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        {% if basket|length == 0 %}
            <div class="col-12">Your Cart is empty <a href="{% url 'frontend:all_products' %}">Shop</a></div>
        {% else %}
        <div class="col">
          <div class="card">
            <div class="card-body p-4">
  
              <div class="row">
  
                <div class="col-lg-7">
                  <!-- <h5 class="mb-3"><a href="#!" class="text-body"><i
                        class="fas fa-long-arrow-alt-left me-2"></i>Continue shopping</a></h5> -->
                  
  
                  <div class="d-flex justify-content-between align-items-center mb-4">
                    <div>
                      <p class="mb-1">Shopping cart</p>
                      <!-- <p class="mb-0">You have 4 items in your cart</p> -->
                    </div>
                    <div>
                      <p class="mb-0"><span class="text-muted">Sort by:</span> <a href="#!"
                          class="text-body">Price <i class="fas fa-angle-down mt-1"></i></a></p>
                    </div>
                  </div>
                  <hr>
                {% for item in basket %}
                {% with product=item.product %}
                  <div class="card mb-3 mb-lg-0 product-item" data-index="{{product.id}}">
                    <div class="card-body">
                      <div class="d-flex justify-content-between">
                        <div class="d-flex flex-row align-items-center">
                          <div>
                            {% for imgg in product.media.all %}
                            {% if imgg.is_featured %}
                            <img
                              src="{{imgg.image.url}}"
                              class="img-fluid rounded-3" alt="Shopping item" style="width: 65px; height: 65px; object-fit: cover;">
                            {% endif %}
                            {% endfor %}
                          </div>
                          <div class="ms-3">
                            <h5>{{product.title|slice:':12'}}</h5>
                            <p><strong>QTY: </strong>{{item.qty}}</p>
                            <!-- <p class="small mb-0">{{product.description|slice:':29'}}......</p> -->
                          </div>
                        </div>
                        <div class="d-flex flex-row align-items-center">
                          <!-- <div style="width: 50px;">
                            <h5 class="fw-normal mb-0">1</h5>
                          </div> -->
                          <div style="width: 100px;">
                            <h5 class="mb-0">${{product.price|intcomma}} <span class="small text-muted">( Each)</span></h5>
                          </div>
                          <a type="button" id="delete-button" data-index="{{product.id}}" class="ps-4 delete-button" style="color: #f00b0b;"><i class="bi bi-trash"></i></a>
                        </div>
                      </div>
                    </div>
                  </div>
                {% endwith %}
                {% endfor %}
  
                </div>
                <div class="col-lg-5">
  
                  <div class="card bg-light text-dark rounded-3">
                    <div class="card-body">
                      <p class="text-center fw-bold">Please make sure you fill the forms below with your information before checking out</p>
                      <hr class="my-4">
  
                      <div class="d-flex justify-content-between">
                        <p class="mb-2">Subtotal</p>
                        <p class="mb-2" id="subtotal">${{basket.get_subtotal_price|intcomma}}</p>
                      </div>
  
                      <div class="d-flex justify-content-between">
                        <p class="mb-2">Shipping</p>
                        <p class="mb-2" id="shipping">${{basket.get_shipping_price}}</p>
                      </div>
  
                      <div class="d-flex justify-content-between mb-4">
                        <p class="mb-2">Total(Incl. taxes)</p>
                        <p class="mb-2" id="total">${{basket.get_total_price|intcomma}}</p>
                      </div>
                      <hr class="my-4">
                      {% if form.errors %}
                        <p class="text-white fw-bold">Please correct the following errors:</p>
                        {% for field in form %}
                            {% if field.errors %}
                            <div class="alert alert-primary" role="alert">
                                {{ field.label }}: {{ field.errors|striptags }}
                            </div>
                            {% endif %}
                        {% endfor %}
                      {% endif %}
                      <form action="{% url 'basket:checkout_order' %}" method="POST">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-6">
                                <div class="mb-3">
                                    <label for="{{ form.c_full_name.id_for_label }}" class="form-label">Full Name</label>
                                    {{form.c_full_name}}
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="mb-3">
                                    <label for="{{ form.c_email.id_for_label }}" class="form-label">Email</label>
                                    {{form.c_email}}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="mb-3">
                                    <label for="{{ form.c_country.id_for_label }}" class="form-label">Country</label>
                                    {{form.c_country}}
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="mb-3">
                                    <label for="{{ form.c_city.id_for_label }}" class="form-label">City</label>
                                    {{form.c_city}}
                                </div>
                            </div>
                        </div>
                        <input type="submit" value="Checkout" class="btn btn-secondary fw-bold text-white w-100 h-auto btn-sm ">
                        
                      </form>
  
                      <!-- <button type="button" class="btn btn-secondary fw-bold text-white w-100 h-auto btn-sm ">
                        Checkout
                      </button> -->
  
                    </div>
                  </div>
  
                </div>
  
              </div>
  
            </div>
          </div>
        </div>
        {% endif %}
      </div>
    </div>
  </section>

  <script>
    $(document).on("click", ".delete-button", function (e) {
    e.preventDefault();
    var prodid = $(this).data("index");
    $.ajax({
      type: "POST",
      url: '{% url "basket:basket_delete" %}',
      data: {
        productid: $(this).data("index"),
        csrfmiddlewaretoken: "{{csrf_token}}",
        action: "post",
      },
      success: function (json) {
        $('.product-item[data-index="' + prodid + '"]').remove();

        if (json.qty == 0) {
          total = 0
          subtotal = 0
        } else {
          total = (parseFloat(json.subtotal) + 11.50).toFixed(2);
          subtotal = json.subtotal
        }

        document.getElementById("subtotal").innerHTML = subtotal;
        document.getElementById("basket-qty").innerHTML = json.qty;
        document.getElementById("total").innerHTML = total;
        document.getElementById("shipping").innerHTML = `$${json.shipping}`;
      },
      error: function (xhr, errmsg, err) {},
    });
  });
  </script>
{% endblock %}